spring:
  mvc:
    locale: pt_BR
    hiddenmethod:
      filter:
        enabled: true
  banner:
    charset: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
  messages:
    basename: messages
    encoding: UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easy
    username: root
    password: easy

server:
  servlet:
    context-path: /easy
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/css,application/json,text/javascript
    min-response-size: 1024

app:
  jwtSecret: 5e21678e6928941ed88184275d052a343a68e1de
  jwtExpirationInMs: 604800000
